
<div class="main-container">
	
	<div class="container-inner">
		<div class="ma-banner7">
				<div class="menu-box1">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Hozmegamenu\Block\Menu')->setTemplate('Plazathemes_Hozmegamenu::verticalmegamenu.phtml')->toHtml();?>
				</div>
				<div class="banner-box2">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
				</div>
				<div class="banner-box3">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_banner_home6')->toHtml(); ?>
				</div>
		</div>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about2')->toHtml(); ?>
	
			
		<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
		
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_conten_home6')->toHtml(); ?>
		
		<div class="ctegory1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('products_categorytab1_home6')->toHtml(); ?>
		</div>	
		<div class="ctegory2">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('products_categorytab2_home6')->toHtml(); ?>
		</div>
		<div class="ctegory3">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('products_categorytab3_home6')->toHtml(); ?>
		</div>
		
		<div class="ctegory4">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('products_categorytab4_home6')->toHtml(); ?>
		</div>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Recentproductslider\Block\Products')->setTemplate('Plazathemes_Recentproductslider::productslider.phtml')->toHtml();?>
	</div>
	<div class="ma-brandslider">
		<div class="container-inner">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
		</div>
	</div>
</div>


